### ISSUE TITLE
AttributeError: module 'os' has no attribute 'uname'

### ISSUE THREAD

**Issue by wndyy** [cvraut/whecho#3]
When I try to configure whecho with command "whecho --init", I get the following error:

Traceback (most recent call last):
  File "C:\Users\wndyy\miniconda3\envs\whecho-env\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\wndyy\miniconda3\envs\whecho-env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\wndyy\miniconda3\envs\whecho-env\Scripts\whecho.exe\__main__.py", line 4, in <module>
  File "C:\Users\wndyy\miniconda3\envs\whecho-env\lib\site-packages\whecho\whecho.py", line 2, in <module>
    from whecho import utilities
  File "C:\Users\wndyy\miniconda3\envs\whecho-env\lib\site-packages\whecho\utilities.py", line 5, in <module>
    from whecho import config
  File "C:\Users\wndyy\miniconda3\envs\whecho-env\lib\site-packages\whecho\config.py", line 12, in <module>
    'os': os.uname().sysname,
AttributeError: module 'os' has no attribute 'uname'

I expected to see the current configuration and the option to edit one of them.

 - OS: Windows 11
 - Version 0.0.2

**Comment by cvraut** [comment]
This seems like a windows specific issue.

Version 0.0.2 was only really tested on ubuntu-latest

**Comment by cvraut** [comment]
https://github.com/cvraut/whecho/pull/4 with version 0.0.3 should have this fixed.

Just tried it on Win10.

you can upgrade whecho via `pip install --force-reinstall whecho`

try it and tell me if you still have an issue :)

**Comment by wndyy** [comment]
installed the latest version and was able to configure it to work on my server. thanks.
